on: push
env:
  VERSION: 0.8.0
  MACOSX_DEPLOYMENT_TARGET: 13.0
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: fzwoch/klumpatsch
    strategy:
      matrix:
        #os: [mingw, linux, macos]
        #arch: [x86_64, arm64]
        os: [mingw]
        arch: [x86_64]
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Setup flex/bison
        run: |
            apt update
            apt install -y flex bison

      - name: Unpack OBS headers
        run: |
          mkdir /tmp/simde
          wget -q -O- https://github.com/simd-everywhere/simde/releases/download/v0.8.2/simde-amalgamated-0.8.2.tar.xz | tar xJ --strip-components 1 -C /tmp/simde
          mkdir /tmp/unpack-obs
          wget -q -O- https://github.com/obsproject/obs-studio/archive/refs/tags/31.1.0.tar.gz | tar xz --strip-components 1 -C /tmp/unpack-obs
          mv /tmp/unpack-obs/libobs /tmp/obs
          touch /tmp/obs/obsconfig.h

      - name: Unpack OBS libraries
        if: ${{ matrix.os == 'windows' }}
        run: |
          if [ "${{ matrix.arch }}" = "amd64" ]; then
            wget -q -O /tmp/obs.zip https://github.com/obsproject/obs-studio/releases/download/31.1.0/OBS-Studio-31.1.0-Windows-x64.zip
          else
            wget -q -O /tmp/obs.zip https://github.com/obsproject/obs-studio/releases/download/31.1.0/OBS-Studio-31.1.0-Windows-arm64.zip
          fi
          unzip -o /tmp/obs.zip "bin/64bit/obs-frontend-api.dll" "bin/64bit/obs.dll" -d /tmp/obs
          mv /tmp/obs/bin/64bit/*.dll /tmp/obs

      - name: Build
        env:
          C_INCLUDE_PATH: /tmp
          LIBRARY_PATH: /tmp/obs
        run: |
          meson setup --buildtype=release -Dstrip=true -Db_lto=true --cross-file=/meson/${{ matrix.os }}-${{ matrix.arch }}.txt build
          meson compile -C build
          meson install -C build

      - name: Upload artifacts
        uses: actions/upload-artifact@v7
        with:
          name: Teleport-${{ env.VERSION }}-${{ matrix.name }}
          path: |
            install.sh
